export  interface Product_data {
    badge: boolean,
    badgeText: string,
    badgeColor: string,
    src: string,
    heading: string,
    newPrice: number,
    oldPrice_h2: boolean,
    oldPrice: number,
    shopBg: string,
}



export const Product_Data: Product_data[] = [
    {
        badge: true,
        badgeText: "New",
        badgeColor: "green",
        src: "/products/card5.png",
        heading: "Library Stool Chair",
        newPrice: 20,
        oldPrice_h2: false,
        oldPrice: 30,
        shopBg: "red",
    },
    {
        badge: true,
        badgeText: "sales",
        badgeColor: "orange",
        src: "/products/product2.png",
        heading: "Library Stool Chair",
        newPrice: 20,
        oldPrice_h2: true,
        oldPrice: 30,
        shopBg: "red",
    },
    {
        badge: false,
        badgeText: "New",
        badgeColor: "green",
        src: "/products/product3.png",
        heading: "Library Stool Chair",
        newPrice: 20,
        oldPrice_h2: false,
        oldPrice: 30,
        shopBg: "red",
    },
    {
        badge: false,
        badgeText: "New",
        badgeColor: "green",
        src: "/products/product4.png",
        heading: "Library Stool Chair",
        newPrice: 20,
        oldPrice_h2: false,
        oldPrice: 30,
        shopBg: "red",
    },
    {
        badge: true,
        badgeText: "New",
        badgeColor: "green",
        src: "/products/cat2.png",
        heading: "Library Stool Chair",
        newPrice: 20,
        oldPrice_h2: false,
        oldPrice: 30,
        shopBg: "red",
    },
    {
        badge: true,
        badgeText: "sales",
        badgeColor: "orange",
        src: "/products/card4.png",
        heading: "Library Stool Chair",
        newPrice: 20,
        oldPrice_h2: true,
        oldPrice: 30,
        shopBg: "red",
    },
    {
        badge: false,
        badgeText: "New",
        badgeColor: "green",
        src: "/products/grid5.png",
        heading: "Library Stool Chair",
        newPrice: 20,
        oldPrice_h2: false,
        oldPrice: 30,
        shopBg: "red",
    },
    {
        badge: false,
        badgeText: "New",
        badgeColor: "green",
        src: "/products/card5.png",
        heading: "Library Stool Chair",
        newPrice: 20,
        oldPrice_h2: false,
        oldPrice: 30,
        shopBg: "red",
    },
    {
        badge: true,
        badgeText: "New",
        badgeColor: "green",
        src: "/products/cat1.png",
        heading: "Library Stool Chair",
        newPrice: 20,
        oldPrice_h2: false,
        oldPrice: 30,
        shopBg: "red",
    },
    {
        badge: true,
        badgeText: "sales",
        badgeColor: "orange",
        src: "/products/product2.png",
        heading: "Library Stool Chair",
        newPrice: 20,
        oldPrice_h2: true,
        oldPrice: 30,
        shopBg: "red",
    },
    {
        badge: false,
        badgeText: "New",
        badgeColor: "green",
        src: "/products/product3.png",
        heading: "Library Stool Chair",
        newPrice: 20,
        oldPrice_h2: false,
        oldPrice: 30,
        shopBg: "red",
    },
    {
        badge: false,
        badgeText: "New",
        badgeColor: "green",
        src: "/products/cat3.png",
        heading: "Library Stool Chair",
        newPrice: 20,
        oldPrice_h2: false,
        oldPrice: 30,
        shopBg: "red",
    },
]